language: python
dist: xenial
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8-dev
    - pypy
    - pypy3
install:
    - pip install zope.testrunner
    - pip install coveralls coverage
    - pip install -U -e .
script:
    - coverage run -m zope.testrunner --path=src --all -v
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
