language: python
sudo: false
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: "3.7"
          dist: xenial
          sudo: true
install:
    - pip install zope.testrunner
    - pip install coveralls coverage
    - pip install -U -e .
script:
    - coverage run -m zope.testrunner --path=src --all -v
after_success:
    - coveralls
notifications:
    email: false
cache:
  pip: true
  directories:
    - eggs/
